// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpBR3xQ0F-NQ7GLZZdEab1N1Dd1gpyW_A',
    appId: '1:208209054222:web:21c73a2f6aefce64598a5f',
    messagingSenderId: '208209054222',
    projectId: 'gasly-2b7d1',
    authDomain: 'gasly-2b7d1.firebaseapp.com',
    storageBucket: 'gasly-2b7d1.firebasestorage.app',
    measurementId: 'G-HBFDF80827',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsg5rFEIMPtKUHG8DrkpDfXuHgCSSWq5Q',
    appId: '1:208209054222:android:07abed18bf24b1b6598a5f',
    messagingSenderId: '208209054222',
    projectId: 'gasly-2b7d1',
    storageBucket: 'gasly-2b7d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQE3chJKaa9Z4Ks82QRNBXAezhNxhQMuw',
    appId: '1:208209054222:ios:f505c7cddede796a598a5f',
    messagingSenderId: '208209054222',
    projectId: 'gasly-2b7d1',
    storageBucket: 'gasly-2b7d1.firebasestorage.app',
    iosClientId: '208209054222-mm867tq5fer5vsjg605776jacmsdlted.apps.googleusercontent.com',
    iosBundleId: 'com.example.gasly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQE3chJKaa9Z4Ks82QRNBXAezhNxhQMuw',
    appId: '1:208209054222:ios:f505c7cddede796a598a5f',
    messagingSenderId: '208209054222',
    projectId: 'gasly-2b7d1',
    storageBucket: 'gasly-2b7d1.firebasestorage.app',
    iosClientId: '208209054222-mm867tq5fer5vsjg605776jacmsdlted.apps.googleusercontent.com',
    iosBundleId: 'com.example.gasly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpBR3xQ0F-NQ7GLZZdEab1N1Dd1gpyW_A',
    appId: '1:208209054222:web:8f7483bbd566932b598a5f',
    messagingSenderId: '208209054222',
    projectId: 'gasly-2b7d1',
    authDomain: 'gasly-2b7d1.firebaseapp.com',
    storageBucket: 'gasly-2b7d1.firebasestorage.app',
    measurementId: 'G-NY0VH2V385',
  );

}